### ISSUE TITLE
Plz fork to make

### ISSUE THREAD

**Issue by Castar** [NaamloosDT/NoNameBancho#1]
Many stuff is made by me, plz fork or delete this repo.

**Comment by NaamloosDT** [comment]
I am going to rewrite the code, so nothing of your code will be left over. Im sorry for not forking.

**Comment by NaamloosDT** [comment]
By the way, your license states that anyone is allowed to redistribute your project with source code.  I'm NOT in any way violating your license. Thanks.

**Comment by Castar** [comment]
In latest version, "This software is Commercial software" included.
Please remove my all code.

**Comment by NaamloosDT** [comment]
Will fork, thx.
